apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: templates.exphost.pl
spec:
  group: exphost.pl
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                template:
                  type: string
                destination:
                  type: string
                destination_type:
                  type: string
  scope: Namespaced
  names:
    plural: templates
    singular: template
    kind: Template
    shortNames:
    - tpl
